server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Avoid redirects to 127.0.0.1 without :8081 when serving prerendered folders.
    absolute_redirect off;
    port_in_redirect off;

    location / {
        try_files $uri $uri/index.html /index.html;
    }
}
